baseURL = "https://intentius.github.io/kubemicrovm-ops/"
title = "kubemicrovm-ops"
theme = "hugo-book"
enableGitInfo = false

[params]
  BookTheme = "auto"
  BookSection = "docs"
  BookToC = true
  BookRepo = "https://github.com/INTENTIUS/kubemicrovm-ops"
  BookEditPath = ""
  BookDateFormat = "2006-01-02"
  BookSearch = true

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 2
  endLevel = 3
